development:
  adapter: mysql2
  database: pl
  username: username
  password: password
  host: 
  port: 3306

production:
  adapter: mysql2
  database: pl
  username: username
  password: password
  host: 
  port: 3306

test:
  adapter: mysql2
  database: pl
  username: username
  password: password
  host: 
  port: 3306
